format = """
$hostname$directory$git_branch$git_status$conda$cmd_duration
$character
"""

[hostname]
ssh_only = true
ssh_symbol = "🌐 "
format = "[$hostname]($style) "
style = "bold green"

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "cyan"
format = "[ $path]($style) "

[git_branch]
style = "yellow"
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
conflicted = "!"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "?"
stashed = "≡"
modified = "*"
staged = "+"
format = "([$all_status$ahead_behind]($style))"
style = "red"

[conda]
symbol = "󰏖 "
format = " [$symbol$environment]($style) "

[python]
disabled = true

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold green) "

[cmd_duration]
min_time = 5000            # show only if >5s
show_milliseconds = false
format = "took $duration "
style = "bold yellow"
