# remap ctrl b to ctrl a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# change split key to | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#switch panes with prefix + arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse
set -g mouse on

# set shell zsh
set-option -g default-shell /usr/bin/zsh

# reload config files
bind r source-file ~/.tmux.conf

#clock mode
setw -g clock-mode-colour yellow

# panes
set -g pane-border-style 'fg=#3b4261'
set -g pane-active-border-style 'fg=#7aa2f7'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#7aa2f7 bg=#1a1b26'

set -g status-left "#[fg=#bb9af7]#{session_name}#[fg=#7aa2f7] | #[fg=#9ece6a]#(whoami)"
set -g status-left-length 15

set -g status-right "#[fg=#e0af68]%Y-%m-%d %H:%M#[fg=#7aa2f7] | #[fg=#7dcfff]#(uptime -p)"
set -g status-right-length 50

setw -g window-status-current-style 'fg=#1a1b26 bg=#7aa2f7'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=#7aa2f7 bg=#16172b'
setw -g window-status-format ' #I #[fg=#c0caf5]#W #[fg=#bb9af7]#F '

setw -g window-status-bell-style 'fg=#e0af68 bg=#f7768e bold'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

### Tmux Plugins ###
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'

# TPM
run '~/.tmux/plugins/tpm/tpm'
