# Add local bin directories to PATH
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#enable vim keybindings
bindkey -v

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"

# Prompt custom
PS1='%F{red}%*%f %F{blue}%m%f %F{green}%~%f %F{red}>%f%F{blue}>%f%F{green}>%f '

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
  fast-syntax-highlighting
  zsh-autocomplete
  fzf-tab
  zsh-history-substring-search
  zsh-completions
)

zstyle ':autocomplete:*' ignored-input 'direnv: *'

#source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

#ALIASES
# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.

# Basic Aliases
alias ls="lsd"
alias la='ls -a'
alias sl='ls'
alias dc='cd'
alias v="nvim"
alias ..="cd .."
alias ...="cd ../.."
alias c="cat"
alias t="tmux"
alias ta="tmux attach"
alias so="source"
alias tl="tail -f"

# Python Stuff
alias python='python3'
alias py='python3'
alias pip='pip3'
alias ca="conda activate"
alias cdv="conda deactivate"
alias uvr="uvicorn main:app --reload"
alias uv="uvicorn"

# Docker Aliases
alias dk="docker"
alias dps="docker ps"
alias dcm="docker compose"
alias dlog="docker logs -f"

# Git Aliases
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit -m"
alias gps="git push"
alias gpl="git pull"
alias gs="git status"
alias gl="git log --oneline --graph --decorate"
alias gco="git checkout"
alias gsw="git switch"
alias gb="git branch"

# Custom Commands and Scripts Aliases
alias tree="python3 ~/dotfiles/scripts/tree.py"
alias xcopy='xclip -selection clipboard -i && sleep 0.1'

xcopylarge() {
    xclip -selection clipboard -i < "$1"
    echo "Copied $(wc -c < "$1") bytes to clipboard"
}

# Server Admin Aliases
alias jl="journalctl -u"
alias jlf="journalctl -f"
alias sc="systemctl"
alias scu="systemctl --user"
alias scs="systemctl status"


jlog() {
    local service="$1"
    local lines="$2"

    if [ -z "$service" ]; then
        echo "Usage: jlog <service> [lines]"
        return 1
    fi

    # Default to 100 lines if none provided
    if [ -z "$lines" ]; then
        lines=100
    fi

    journalctl -u "$service.service" -n "$lines" --no-pager -o cat
}



export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/tmp/google-cloud-sdk/path.zsh.inc' ]; then . '/tmp/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/tmp/google-cloud-sdk/completion.zsh.inc' ]; then . '/tmp/google-cloud-sdk/completion.zsh.inc'; fi
#export PATH="$HOME/.pyenv/bin:$PATH"
#eval "$(pyenv init --path)"
# source ~/miniconda3/etc/profile.d/conda.sh  # commented out by conda initialize


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/simon/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/simon/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/simon/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/simon/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Starship Prompt
eval "$(starship init zsh)"
export PATH="/snap/bin:$PATH"

# Direnv
export DIRENV_LOG_FORMAT=""
eval "$(direnv hook zsh)"

# Zoxide (smart cd)
eval "$(zoxide init zsh)"

# uv (Python package manager) - add to PATH
export PATH="$HOME/.cargo/bin:$PATH"

# Add global ruff configuration
export RUFF_CONFIG="$HOME/.config/ruff/ruff.toml"
